apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archiva.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archiva.labels" . | nindent 4 }}
data:
  archiva.xml: |-
    {{ .Values.archivaConf | nindent 4 }}
