apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "weblate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "weblate.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "weblate.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "weblate.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "weblate.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "weblate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: busybox
          command:
            - sh
            - -c
          args:
            - chown -R {{ .Values.chownDataVolumeAs }} /app/data;
          volumeMounts:
            - mountPath: "/app/data"
              name: data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "weblate.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.envFrom }}
          envFrom:
        {{- end }}
          volumeMounts:
            - mountPath: "/app/data"
              name: data
        {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
{{- end }}
