{{- if .Values.rbac.create }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-resource-report.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-resource-report.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-resource-report.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-resource-report.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}