{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-resource-report.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-resource-report.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "services"]
  verbs:
    - get
    - list
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs:
    - list
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs:
    - get
    - list
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["heapster"]
  verbs:
    - get
# allow reading VPAs to get resource recommendations
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs:
    - get
    - list
# allow reading Deployments and StatefulSets to get matching Pods for VPAs
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
  verbs:
    - get
    - list
{{- end -}}
