apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
data:
  gitlab.rb: {{ .Values.gitlabConf | b64enc | quote }}
