apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
    component: 'ui'
spec:
  ports:
    - name: http-gitlab-exp
      port: 9168
      targetPort: http-gitlab-exp
    - name: http-node-exp
      port: 9100
      targetPort: http-node-exp
    - name: http-nginx-exp
      port: 8060
      targetPort: http-nginx-exp
    - name: https
      port: 443
      targetPort: https
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
