{{- if or (.Values.serviceAccount.create) (.Values.backupCronJob.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitlab.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
