{{- if .Values.worker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildbarn.fullname" (list . "worker") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "buildbarn.labels" (list . "worker") | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - name: {{ .Values.worker.service.name }}
      port: {{ .Values.worker.service.port }}
      targetPort: http
  selector:
    {{- include "buildbarn.selectorLabels" (list . "worker") | nindent 4 }}
{{- end }}
