apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "altinity-clickhouse-operator.fullname" . }}-confd-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
data:
{{- if .Values.configs.confdFiles }}
  {{- toYaml .Values.configs.confdFiles | nindent 2 }}
{{ end }}
