kind: Service
apiVersion: v1
metadata:
  name: {{ include "altinity-clickhouse-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8888
      name: clickhouse-operator-metrics
      targetPort: metrics
  selector:
    {{- include "altinity-clickhouse-operator.selectorLabels" . | nindent 4 }}
