---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "external-secrets-operator.labels" . | nindent 4 }}
  name: {{ include "external-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "external-secrets-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "external-secrets-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ include "external-secrets-operator.tag" . }}"
        name: manager
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      serviceAccountName: {{ include "external-secrets-operator.fullname" . }}
      terminationGracePeriodSeconds: 10
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
