apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gke-preemptible-notifier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gke-preemptible-notifier.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
