apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeppelin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zeppelin.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zeppelin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "zeppelin.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rpc
              containerPort: 12320
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_WAR_TEMPDIR
              value: "/zeppelin-tmp/war"
        {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: {{ include "zeppelin.fullname" . }}-tmp
              mountPath: /zeppelin-tmp
        {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "zeppelin.fullname" . }}-tmp
          emptyDir: {}
    {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
