apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zeppelin.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zeppelin.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zeppelin.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zeppelin.serviceAccountName" . }}
