apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 12320
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 4040
      targetPort: http-spark
      protocol: TCP
      name: http-spark
  selector:
    {{- include "zeppelin.selectorLabels" . | nindent 4 }}
