apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
