apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
