apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "config-connector-templater.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "config-connector-templater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "config-connector-templater.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "config-connector-templater.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
