apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "config-connector-templater.fullname" . }}-controller-manager
  labels:
    {{- include "config-connector-templater.labels" . | nindent 4 }}
