name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
#        env:
#          CT_CHART_DIRS: "/github/workspace"
        with:
          image: quay.io/helmpack/chart-testing:v3.0.0-beta.2
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          install_local_path_provisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
#        env:
#          CT_CHART_DIRS: "/github/workspace"
        with:
          image: quay.io/helmpack/chart-testing:v3.0.0-beta.2
          command: install
          config: ct.yaml
